main: mxrlin.file.FileManager
name: FileManager
version: 1.1.1
description: Manage all of your files ingame!
api-version: 1.18
author: Mxrlin
commands:
  filemanager:
    description: Open the File Manager.
    permission: filemanager.use
    usage: "Usage: /filemanager"
permissions:
  filemanager.use:
    description: Used to execute /filemanager.
    default: op